name: Push/pull 
on: 
  push:
  pull_request:
jobs:
  fmt:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
      - name: cargo fmt
        run: cargo fmt
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions [Bot]"
          git add -A
          git commit -m "Automatic formatting" -a
          git push
  # build:
  #   name: Rust project - latest
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       # include:
  #       #   - rust_target: x86_64-unknown-linux-gnu
  #       #     artifact_name: tuxmux-glibc-amd64
  #       #   - rust_target: x86_64-unknown-linux-musl
  #       #     artifact_name: tuxmux-musl-amd64
  #       #   - rust_target: aarch64-unknown-linux-gnu
  #       #     artifact_name: tuxmux-glibc-aarch64
  #       #   - rust_target: aarch64-unknown-linux-musl
  #       #     artifact_name: tuxmux-musl-aarch64
  #       #   - rust_target: armv7-unknown-linux-gnueabihf
  #       #     artifact_name: tuxmux-glibc-aarch64
  #       toolchain:
  #         - stable
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Rust
  #       uses: dtolnay/rust-toolchain@stable
  #       with:
  #         toolchain: stable
  #         target: ${{ matrix.rust_target }}
  #     - name: Building client binary
  #       run: cargo build --release --bin client --verbose
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: tuxmux-client-glibc-amd64
  #         path: target/release/client
  #         if-no-files-found: error
  #     - name: Building server binary
  #       run: cargo build --release --bin server --verbose
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: tuxmux-server-glibc-amd64
  #         path: target/release/server
  #         if-no-files-found: error